### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by DanBrown47** [amschel99/Veestream#6]
Hello wave

I research to fix vulnerabilities in OSS. ☠️ 

Could you add a SECURITY.md file with an e-mail address? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍🏽

**Comment by amschel99** [comment]
resolved

**Comment by amschel99** [comment]
Hi, I resolved the issue.
